esphome:
  name: $name


# Enable logging
logger:

esp32:
  board: $board
  framework:
    type: arduino

# Enable Home Assistant API
api: 
  password: $api_pwd
  encryption: 
    key: $api_enc_key

ota:
  safe_mode: false
  password: $ota_pwd

wifi:
  ssid: $wifi_ssid
  password: $wifi_pwd

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $ap_fallback_ssid
    password: $ap_fallback_pwd
captive_portal: