
# Enable Home Assistant API
api: 
  password: !secret api_password
  encryption: 
    key: !secret api_key

ota:
  safe_mode: false
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password