esphome:
  name: $config_name


# Enable logging
logger:
  level: $config_logger_level

esp32:
  board: $config_board
  framework:
    type: arduino

# Enable Home Assistant API
api: 
  # password: $config_api_pwd
  encryption: 
    key: $config_api_enc_key

ota:
  safe_mode: false
  password: $config_ota_pwd

wifi:
  ssid: $config_wifi_ssid
  password: $config_wifi_pwd

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $config_ap_fallback_ssid
    password: $config_ap_fallback_pwd
captive_portal:
