apds9960:
  address: 0x39
  update_interval: 1s
  proximity_gain: 8x
  ambient_light_gain: 4x
  gesture_gain: 8x
  gesture_led_drive: 12.5mA
  gesture_wait_time: 2.8ms



text_sensor: 
  - platform : template 
    name: "Sauna Utility Gesture Status"
    icon: mdi:gesture
    id : direction_status


sensor:
  - platform: apds9960
    name: "Sauna Utility Proximity Channel"
    id: prox
    type: PROXIMITY    
    on_value_range:
      - below: 2.0
        then:
          - binary_sensor.template.publish: 
              id: proximity
              state: OFF
      - above: 2.0
        below: 50.0
        then:
          - binary_sensor.template.publish: 
              id: proximity
              state: ON
      - above: 50.0
        then:
          - binary_sensor.template.publish: 
              id: proximity
              state: OFF

binary_sensor:
  
   

  - platform: apds9960
    id: gesture_up
    direction: UP
    on_state:
      - binary_sensor.template.publish: 
          id: proximity
          state: ON
      - text_sensor.template.publish: 
          id: direction_status
          state: "UP"

  - platform: apds9960
    id: gesture_down
    direction: DOWN
    on_state:
      - binary_sensor.template.publish: 
          id: proximity
          state: ON
      - text_sensor.template.publish: 
          id: direction_status
          state: "DOWN"
    
  - platform: apds9960
    id: gesture_right
    direction: RIGHT
    on_state:
      - binary_sensor.template.publish: 
          id: proximity
          state: ON 
      - text_sensor.template.publish: 
          id: direction_status
          state: "RIGHT"
    
  - platform: apds9960
    id: gesture_left
    direction: LEFT
    on_state:
      - binary_sensor.template.publish: 
          id: proximity
          state: ON 
      - text_sensor.template.publish: 
          id: direction_status
          state: "LEFT"