apds9960:
  address: 0x39
  update_interval: $gesture_update_interval
  proximity_gain: $gesture_proximity_gain
  ambient_light_gain: $gesture_ambient_light_gain
  led_drive: $gesture_pri_led_drive 
  gesture_gain: $gesture_gain
  gesture_led_drive: $gesture_led_drive
  gesture_wait_time: $gesture_wait_time
  

text_sensor: 
  - platform : template 
    name: "Sauna Utility Gesture Status"
    icon: mdi:gesture
    id : direction_status


sensor:
  - platform: apds9960
    name: "Sauna Utility Proximity Channel"
    id: prox
    type: PROXIMITY    
    filters:
      - exponential_moving_average:
          alpha: 0.1
          send_every: 1
    on_value_range:
      - below: $gesture_prox_min
        then:
          - binary_sensor.template.publish: 
              id: $gesture_prox_id
              state: OFF
      - above: $gesture_prox_min
        below: $gesture_prox_max
        then:
          - binary_sensor.template.publish: 
              id: $gesture_prox_id
              state: ON
      - above: $gesture_prox_max
        then:
          - binary_sensor.template.publish: 
              id: $gesture_prox_id
              state: OFF

binary_sensor:
  
   

  - platform: apds9960
    id: gesture_up
    direction: UP
    on_state:
      - binary_sensor.template.publish: 
          id: $gesture_prox_id
          state: ON
      - binary_sensor.template.publish: 
          id: $gesture_prox_id
          state: OFF
      - text_sensor.template.publish: 
          id: direction_status
          state: "UP"

  - platform: apds9960
    id: gesture_down
    direction: DOWN
    on_state:
      - binary_sensor.template.publish: 
          id: $gesture_prox_id
          state: ON
      - binary_sensor.template.publish: 
          id: $gesture_prox_id
          state: OFF
      - text_sensor.template.publish: 
          id: direction_status
          state: "DOWN"
    
  - platform: apds9960
    id: gesture_right
    direction: RIGHT
    on_state:
      - binary_sensor.template.publish: 
          id: $gesture_prox_id
          state: ON
      - binary_sensor.template.publish: 
          id: $gesture_prox_id
          state: OFF 
      - text_sensor.template.publish: 
          id: direction_status
          state: "RIGHT"
    
  - platform: apds9960
    id: gesture_left
    direction: LEFT
    on_state:
      - binary_sensor.template.publish: 
          id: $gesture_prox_id
          state: ON
      - binary_sensor.template.publish: 
          id: $gesture_prox_id
          state: OFF
      - text_sensor.template.publish: 
          id: direction_status
          state: "LEFT"